version: "24.0.2"

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./api/openapi.yaml:/openapi.yaml # Swagger File
    environment:
      SWAGGER_JSON: /openapi.yaml # Swagger File

  swagger-api:
    image: stoplight/prism:latest
    container_name: "swagger-api"
    ports:
      - "8003:4010"
    command: mock -h 0.0.0.0 /openapi.yaml # Swagger File
    volumes:
      - ./api/openapi.yaml:/openapi.yaml # Swagger File
