version: '3.8'
services:
  redoc:
    image: redocly/redoc
    ports:
      - 8001:80
    volumes:
      - ./api/merged.yaml:/usr/share/nginx/html/merged.yaml
    environment:
      SPEC_URL: merged.yaml
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8002:8080
    volumes:
      - ./api/merged.yaml:/usr/share/nginx/html/merged.yaml
    environment:
      API_URL: merged.yaml
  api-mock:
    image: danielgtaylor/apisprout
    ports:
      - 8003:8000
    volumes:
      - ./api/merged.yaml:/merged.yaml
    entrypoint: /usr/local/bin/apisprout /merged.yaml --watch
  redoc-cli:
    build: ./docker/redoc-cli
    volumes:
      - ./api:/data
  swagger-merger:
    build: ./docker/swagger-merger
    volumes:
      - ./docker/swagger-merger/watch.js:/watch.js
      - ./api:/data
    environment:
      NODE_PATH: /usr/local/lib/node_modules
    entrypoint: node /watch
