openapi: 3.1.0
info:
  version: 1.0.0
  title: KINTAI
  description: 勤怠管理アプリ「KINTAI」
servers:
  - url: http://localhost:8003
    description: ローカル環境
tags:
  - name: admin
    description: 管理者の操作
  - name: employee
    description: 従業員の操作
paths:
  /api/v1/admin/current_admin:
    get:
      summary: ログインしている管理者の取得
      tags:
        - admin
      operationId: getCurrentAdmin
      deprecated: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: example 管理者
                  email:
                    type: string
                    example: kintai@example.com
                required:
                  - id
                  - name
                  - email
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: Unauthorized
                  message:
                    type: array
                    items:
                      example: ログインしてください
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: Forbidden
                  message:
                    type: array
                    items:
                      example: 権限がありません
        '404':
          description: NotFound
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: NotFound
                  message:
                    type: array
                    items:
                      example: 対象データが存在しません。
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: InternalServerError
                  messages:
                    type: array
                    items:
                      type: string
                      example: サーバーエラー
  /api/v1/admin/admins:
    get:
      summary: 全ての管理者の取得
      tags:
        - admin
      operationId: getAdmins
      deprecated: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: example 管理者
                        email:
                          type: string
                          example: kintai@example.com
                      required:
                        - id
                        - name
                        - email
                  pagenation:
                    type: object
                    properties:
                      current:
                        type: integer
                        example: 1
                      pages:
                        type: integer
                        example: 3
                      totalCount:
                        type: integer
                        example: 30
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: Unauthorized
                  message:
                    type: array
                    items:
                      example: ログインしてください
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: Forbidden
                  message:
                    type: array
                    items:
                      example: 権限がありません
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: InternalServerError
                  messages:
                    type: array
                    items:
                      type: string
                      example: サーバーエラー
    post:
      summary: 管理者作成
      tags:
        - admin
      operationId: createAdmin
      deprecated: false
      requestBody:
        description: 管理者登録情報
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                name:
                  type: string
                  example: example 管理者
                email:
                  type: string
                  example: kintai@example.com
              required:
                - id
                - name
                - email
      responses:
        '201':
          description: Success
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: BadRequest
                  message:
                    type: array
                    items:
                      example: 〇〇を入力してください
  /api/v1/admin/admins/{id}:
    get:
      summary: 管理者の取得
      tags:
        - admin
      operationId: getAdmin
      deprecated: false
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: example 管理者
                  email:
                    type: string
                    example: kintai@example.com
                required:
                  - id
                  - name
                  - email
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: Unauthorized
                  message:
                    type: array
                    items:
                      example: ログインしてください
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: Forbidden
                  message:
                    type: array
                    items:
                      example: 権限がありません
        '404':
          description: NotFound
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: NotFound
                  message:
                    type: array
                    items:
                      example: 対象データが存在しません。
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                    example: InternalServerError
                  messages:
                    type: array
                    items:
                      type: string
                      example: サーバーエラー
