openapi: 3.1.0

info:
  version: 1.0.0
  title: "KINTAI"
  description: >-
    勤怠管理アプリ「KINTAI」

servers:
  - url: "http://localhost:8003"
    description: "ローカル環境"

tags:
  - name: "admin"
    description: "管理者の操作"
  - name: "employee"
    description: "従業員の操作"

paths:
  /api/v1/admin/current_admin:
    $ref: "./paths/admin/currentAdmin.yml"
  /api/v1/admin/admins:
    $ref: "./paths/admin/admins.yml"
  /api/v1/admin/admins/{id}:
    $ref: "./paths/admin/adminById.yml"
  /api/v1/admin/employees:
    $ref: "./paths/admin/employees.yml"
  /api/v1/admin/employees/{id}:
    $ref: "./paths/admin/employeeById.yml"
  /api/v1/admin/shifts:
    $ref: "./paths/admin/shifts.yml"
  /api/v1/admin/shifts/{id}:
    $ref: "./paths/admin/shiftById.yml"
  /api/v1/admin/absences/{id}:
    $ref: "./paths/admin/absenceById.yml"
  /api/v1/admin/notifications:
    $ref: "./paths/admin/notifications.yml"
  /api/v1/admin/unappliedEmployees:
    $ref: "./paths/admin/unappliedEmployees.yml"
